[build]
  command = "npm install && npm run netlify-build"
  functions = "functions"
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "17.9.0"
  NODE_OPTIONS = --openssl-legacy-provider