# Node.js CI by Github Workflow
name: Express CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - name: Test
        env: # repo secrets as environment variable
          IFTTT_KEY: ${{ secrets.IFTTT_KEY }}
        run: |
          printenv
          npx prettier --check .
          npm run test:coverage
      - name: Test Summary
        uses: test-summary/action@v1
        with:
          paths: |
            test-results.xml
          output: "test-summary.md"
        if: always()
      - name: PR Comment
        uses: machine-learning-apps/pr-comment@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: test-summary.md
        if: github.event_name == 'pull_request'
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
