# Node.js CI by Github Workflow
name: Express CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

      - uses: pnpm/action-setup@v2.2.3
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - run: pnpm install --frozen-lockfile

      - name: Test
        env: # repo secrets as environment variable
          IFTTT_KEY: ${{ secrets.IFTTT_KEY }}
        run: |
          printenv
          pnpm run format
          pnpm run test:fmt
          pnpm run test:coverage

      - name: Test Summary
        uses: test-summary/action@v1
        with:
          paths: |
            test-results.xml
          output: "test-summary.md"
        if: always()
      - name: PR Comment
        uses: machine-learning-apps/pr-comment@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: test-summary.md
        if: github.event_name == 'pull_request'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Generate Swagger Spec JSON
        run: |
          pnpm install
          pnpm run swagger

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: auto-format code style [ci skip]"
          file_pattern: ":/*.*"
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
